#!/usr/bin/env python3
"""Verify a Skill repository (generated by Skill Repo Forge or laid out the same way).

Default mode is static and never executes code from the repository: it checks
layout, audits the Skill, and compares dist/skill.zip with the Skill folder
in-process. Pass --run-checks to also execute the repository's own validator
and tests; do that only for repositories you generated or trust.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import skill_rules as sr  # noqa: E402
from audit_skill import inspect_root  # noqa: E402

REQUIRED = [
    "README.md",
    ".gitignore",
    ".gitattributes",
    ".github/workflows/validate-skill.yml",
    "scripts/validate_skill.py",
    "scripts/build_dist.py",
    "scripts/skill_rules.py",
    "tests/test_skill_layout.py",
    "dist/skill.zip",
]
REPO_ONLY = {"README.md", "CONTRIBUTING.md", "SECURITY.md", "CHANGELOG.md", ".gitignore", ".gitattributes"}


def verify(repo: Path, target: str = "all", run_checks: bool = False) -> dict:
    target = sr.normalize_target(target)
    repo = Path(repo).expanduser().resolve()
    findings = []

    def add(sev, code, msg, path=None):
        findings.append({"severity": sev, "code": code, "message": msg, "path": path})

    for rel in REQUIRED:
        if not (repo / rel).is_file():
            add("blocker" if rel in ("README.md", "dist/skill.zip") else "warning", "missing_repo_file", f"Missing {rel}", rel)
    if not any((repo / n).is_file() for n in ("LICENSE", "LICENSE.md", "LICENSE.txt")):
        add("warning", "no_license", "No LICENSE file: others cannot legally reuse this Skill", "LICENSE")

    skill_root, roots = sr.find_repo_skill(repo)
    audit = None
    if skill_root is None:
        add("blocker", "skill_root_count", f"Expected exactly one skills/<name>/SKILL.md, found {len(roots)}", "skills/")
    else:
        audit = inspect_root(skill_root, target)
        for f in audit["findings"]:
            add(f["severity"], f["code"], f["message"], f"skills/{skill_root.name}/{f['path']}" if f.get("path") else None)
        zip_path = repo / "dist" / "skill.zip"
        if zip_path.is_file():
            for d in sr.compare_zip(skill_root, zip_path, skill_root.name):
                add("blocker", "dist_out_of_sync", d, "dist/skill.zip")
            try:
                with zipfile.ZipFile(zip_path) as zf:
                    names = zf.namelist()
                if any(n.count("/") == 1 and n.split("/", 1)[1] in REPO_ONLY for n in names):
                    add("warning", "repo_file_in_skill_zip", "Repository documentation is inside skill.zip", "dist/skill.zip")
            except zipfile.BadZipFile:
                pass
        readme = repo / "README.md"
        if readme.is_file() and f"--skill {skill_root.name}" not in readme.read_text(encoding="utf-8", errors="replace"):
            add("warning", "readme_install_command", "README does not show an `npx skills add ... --skill <name>` command", "README.md")

    commands = []
    if run_checks:
        for cmd in (["scripts/validate_skill.py"], ["scripts/build_dist.py", "--check"], ["-m", "unittest", "discover", "-s", "tests"]):
            if cmd[0].endswith(".py") and not (repo / cmd[0]).is_file():
                continue
            if cmd[0] == "-m" and not (repo / "tests").is_dir():
                continue
            p = subprocess.run([sys.executable, *cmd], cwd=repo, capture_output=True, text=True, check=False, timeout=300)
            commands.append({"command": "python3 " + " ".join(cmd), "returncode": p.returncode,
                             "stdout": p.stdout[-4000:], "stderr": p.stderr[-4000:]})
            if p.returncode != 0:
                add("blocker", "repo_check_failed", f"`python3 {' '.join(cmd)}` exited with {p.returncode}")

    status = "fail" if any(f["severity"] == "blocker" for f in findings) else "pass"
    return {
        "status": status,
        "repo": str(repo),
        "target": target,
        "skill_name": skill_root.name if skill_root else None,
        "executed_repo_code": run_checks,
        "findings": findings,
        "commands": commands,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repo")
    ap.add_argument("--target", default="all", help="all (default), portable, claude, or openai")
    ap.add_argument("--run-checks", action="store_true", help="also execute the repo's validator and tests (trusted repos only)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    try:
        result = verify(Path(args.repo), args.target, args.run_checks)
    except ValueError as e:
        ap.error(str(e))
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"Status: {result['status'].upper()}   Skill: {result['skill_name']}   Target: {result['target']}")
        for f in result["findings"]:
            loc = f" [{f['path']}]" if f.get("path") else ""
            print(f"- {f['severity'].upper()} {f['code']}{loc}: {f['message']}")
        for c in result["commands"]:
            print(f"- ran `{c['command']}`: exit {c['returncode']}")
        if not args.run_checks:
            print("(static mode: repository code was not executed; add --run-checks for trusted repos)")
    return 0 if result["status"] == "pass" else 2


if __name__ == "__main__":
    raise SystemExit(main())
